<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LGDN14993-W10" ignored="0" name="Test" tests="13" failures="2" timestamp="29 Jan 2021 09:07:07 GMT" time="221.304" errors="0">
  <testcase name="TC01" time="6.121" classname="Testcases.RailWay.railways.TC01_LoginWithValidAccount"/>
  <testcase name="TC02" time="3.686" classname="Testcases.RailWay.railways.TC02_LoginWithBlankUsername"/>
  <testcase name="TC04" time="1.3" classname="Testcases.RailWay.railways.TC04_LoginFromBookTicket"/>
  <testcase name="TC05" time="9.985" classname="Testcases.RailWay.railways.TC05_LoginSeveralTimes">
    <failure type="java.lang.AssertionError" message="expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at Testcases.RailWay.railways.TC05_LoginSeveralTimes.TC05(TC05_LoginSeveralTimes.java:31)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TC05 -->
  <testcase name="TC06" time="6.702" classname="Testcases.RailWay.railways.TC06_HomeLogged"/>
  <testcase name="TC07" time="4.534" classname="Testcases.RailWay.railways.TC07_CreateAccount"/>
  <testcase name="TC08" time="4.155" classname="Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Testcases.RailWay.railways.TC08_LoginWithNotActivatedAccount.TC08(TC08_LoginWithNotActivatedAccount.java:47)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TC08 -->
  <testcase name="TC09" time="8.318" classname="Testcases.RailWay.railways.TC09_ChangeNewPassword"/>
  <testcase name="TC10" time="4.649" classname="Testcases.RailWay.railways.TC10_RegisterWithInvalidAccount"/>
  <testcase name="TC11" time="4.302" classname="Testcases.RailWay.railways.TC11_RegisterWithInvalidAccount"/>
  <testcase name="TC14" time="9.578" classname="Testcases.RailWay.railways.TC14_BookTicket"/>
  <testcase name="TC15" time="5.995" classname="Testcases.RailWay.railways.TC15_BookTicketFrTrainTimetable"/>
  <testcase name="TC16" time="11.597" classname="Testcases.RailWay.railways.TC16_CancelTicket"/>
</testsuite> <!-- Test -->
